name: Deploy Node App to DockerHub

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Step 3: Install dependencies and test (if you have tests)
      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: echo "No tests defined"  # Replace with `npm test` if you have tests

      # Step 4: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build and push Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest

      # Step 7: Run container from pushed image
      - name: Run container (for testing)
        run: |
          docker run -d -p 3000:3000 --name node-app-test ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
          sleep 5
          curl http://localhost:3000 || echo "App did not respond"
